### ISSUE TITLE
ServiceX Transform Response Should Provide Minio URL

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#146]
_As an analyzer I want to know the Minio URL so I can download my results_

## Assumptions
1. Added to app.conf
2. Provided as part of the status response

## Acceptance Criteria
1. Deploy a serviceX with a public Minio Endpoint
2. Submit a request
3. See the URL for Minio in the status response
4. Able to access via browser

**Comment by gordonwatts** [comment]
I just wanted to say: YES. I've been wanting to see this for a while. This is something that will have to be fed from the helm chart. But this is great.

Please do make sure to let me know as soon as it is understood how this will work so that we can start to understand how to put this into the frontend code.
