### ISSUE TITLE
ingress settings

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#230]
Application ingress points to three services:
  xaod.servicex.ssl-hep.org
                             /minio               xaod-minio:9000 (192.168.38.190:9000)
                             /servicex/internal   default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
                             /                    xaod-servicex-app:8000 (192.168.48.136:5000)

it should not point to minio as minio has its own ingress.
it should not point to a default backend as there is no service listening on port 80.

**Comment by BenGalewsky** [comment]
Removed the unused Ingress path via PR #236 

The reference to the `default-http-backend` is a trick to hide the `/internal` path from the outside. Anyone attempting to access the internal endpoints via this ingress will get an nginx 503 error.

**Comment by BenGalewsky** [comment]
Also, in case anyone is wondering why we use the Minio sub chart's ingress instead of adding it as a path here, the [Minio SDK](https://docs.min.io/docs/python-client-api-reference.html) only accepts a hostname and port to connect to the service. As per the S3 standard, there is no option to use an http path.

**Comment by AndrewEckart** [comment]
Resolved in #236.
