### ISSUE TITLE
Option to write transformer results to persistent volume

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#262]
# Story
_As a coffea-casa user I want to have my transformer results written to a POSIX persistent volume so other tools in the facility can work with the data_

# Assumptions
1. New `result-destination` option: `volume`
2. New settings in `values.yaml` for helm chart 
- transformer.persistence.existingClaim
- transformer.persistence.storageClass
- transformer.persistence.size
- transformer.persistence.annotations
- transformer.persistence.subdir
3. If existingClaim is None, TransformerManager in app will create a read-write-many PVC
4. The new or existing PVC will be mounted into each of the transformer pods
5. Results will be written to a directory under the PVC mount/subdir directory named after the transform request UID

# Acceptance Criteria
1. Given I have a transform request with `result-destination: volume` and I have provided a valid persistent volume claim when I submit the transform then it should run without errors and the transform files are available in the provided `subdir` under a directory named after the transform request's UID

**Comment by gordonwatts** [comment]
Thinking about this a little - does this need to be part of the core ServiceX, or could it be an "add-on"? You could imagine, for example, a caching pass-through that would take a request, see it wanted to write to its cache, made a minor mod to its request, then send it on to servicex proper, when the data arrived, stream it to a local disk...

I'm asking because a possible goal is to keep servicex itself clean and neat an simple, and then build a ecosystem of various pip-lines behind it that add functionality that isn't "servicex" behavior. Thus the core can concentrate on workflow, and everything else around it can concentrate on ... well... everything else.

I'm sure this doesn't always make sense, there are many things that should be part of the core product. But as a way to avoid feature creep...

BTW - this was my idea for a caching front-end. You don't modify ServiceX, but build a container that re-writes queries as they go by, caches them locally, etc.

**Comment by BenGalewsky** [comment]
Done and released in RC4
