### ISSUE TITLE
Generate trivial Transformer code from FuncADL Select

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#30]
# Story
_As an analyzer I want the transformer to select columns based on my selection so I can generate n-tuples for my research_

# Acceptance Criteria
1. Given a valid selection in the text language when I run the transformer then I should get the selected columns back
2. Given a selection text and the text contains syntax errors when I run the transformer then I should receive an error

# Assumptions
1. The ADL code is passed into the serviceX request as a JSON property
2. Parser and code generator added to the transformer code
3. The generated code looks mostly like the current code that reads attributes from the selected branches
4. The rest of the transformer runs as previously

**Comment by gordonwatts** [comment]
This looks like the generation of a component that will translate the new adl into the old python stuff from the assumption. This is a stepping stone to getting the full C++ backend in, right?

This makes me a little uncomfortable because it is creating something that will be thrown away: once the C++ back end comes in, we will likely have less use for the current backend.

If I remove some of your assumptions, this is the story I'd write for putting the C++ transformer in, which I guess is at the base of what I'm nervous about.

**Comment by BenGalewsky** [comment]
Closed since this is now subsumed by #31
