### ISSUE TITLE
Flat Root File Transformer

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#44]
# Story
_As an Analyzer I want to extract columns out of a flat root dataset so I can efficiently perform my analysis_

# Assumptions
1. Flat Root files can be read using uproot

# Acceptance Criteria
1. Submit a transformation request with a nanoAOD dataset and a list of CMS columns. Receive the requested data in Kafka or Minio object store

Tasks 
- [x] Chunk Uproot Awkward Arrays
- [x] Update Preflight check
- [ ] Refactor common transformer code into package
- [ ] Publish library of common transformer code on PyPI
- [ ] Develop process to build flat root docker images for transformer

**Comment by BenGalewsky** [comment]
Upon further reflection, it looks like we may want to pull information out of different trees in a single transform. We are going to change the `columns` definition to be _tree-name_._branch-name_

So `Events.Electron_phi`

**Comment by robrwg** [comment]
I understand there has been recent progress.  Can this be updated with the latest? @BenGalewsky

**Comment by gordonwatts** [comment]
Wanted @masonproffitt to see this - because of some of his code is going to need to work here.

That said, I'd like to better understand these file formats... Is it the case that the many tree's are "linked" or are they different? Linked, in the sense that one tree contains all the electron leaves, a second tree contains all the muon trees, etc.? Or are the trees different things, and you would never try to use the data accross the trees at the "same time"?

**Comment by BenGalewsky** [comment]
Each tree has the exact same set of branches. They represent different systematic variations. While each tree in theory contains the same set of branches and covers the same events, it doesn't make sense to treat them as linked since the selection criteria will most certainly filter out different events in each tree.

**Comment by BenGalewsky** [comment]
I'm going to close this since it's really covered in #102
