### ISSUE TITLE
Prometheus Instrumentation for Services

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#54]
# Story
_As a ServiceX Administrator I want the services to publish metrics to Prometheus so I can monitor and tune the system correctly_

# Assumptions
1. Use the [prometheus client](https://www.robustperception.io/instrumenting-python-with-prometheus)

# Acceptance Criteria
1. Given I log into Prometheus when I run a transform I can see the following metrics for the Transformer:
- Number of events transformed
- Number of bytes input
- Number of bytes output
- Request ID
- Events/Second 

2. Given I log into Prometheus when I run a transform I can see the following metrics for the DID Finder:
- Number of files found

**Comment by AndrewEckart** [comment]
Okay, I'm ready to put some ideas in writing here. First, we need to define some metrics for Prometheus to scrape. There are 3 primary types of metrics:
- Counters: monotonically increasing, usually integral (e.g. total requests)
- Gauges: can go up/down, (e.g. CPU usage)
- Histograms: frequencies of predefined buckets (e.g. response time)

Here's a proposed implementation to meet the specifications above:
- `sx_transformed_events_total` (Counter) - labeled by transformation request ID and pod. Events per second can be queried with the [`rate` query function](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate).
- `sx_input_bytes_total` (Counter) - labeled by transformation request ID and pod.
- `sx_output_bytes_total` (Counter) - labeled by transformation request ID and pod.

We will want a Grafana dashboard with dropdowns to filter by transformation request ID, and then by pod, allowing ServiceX operators to quickly see performance for a specific transformation request.

In order to actually instrument the transformers, we may need to use a [Prometheus Pushgateway](https://github.com/prometheus/pushgateway). This is because if we scrape the transformers directly, their metrics will disappear from Prometheus as soon as they finish running. We make the further assumption that we won't need aggregation/distributed counting - if this is required, we'll have to explore the third-party [aggregation gateway](https://github.com/weaveworks/prom-aggregation-gateway) by Weaveworks. 

However, if we are only interested in metrics for *ongoing* transformation requests, i.e. those whose transformers are still around, we will need to delete them manually. An alternative is to avoid using the Pushgateway altogether and scrape the transformers directly, but this requires programmatic creation/deletion of K8s Services and ServiceMonitors corresponding to each transformer.

The best place to actually put the instrumentation code is likely the [ServiceX transformer](https://github.com/ssl-hep/ServiceX_transformer) library, possibly in the `ServiceXAdapter` class.

**Comment by BenGalewsky** [comment]
A few thoughts here:
1. I think the best place to report metrics will be in each transformer's `transform_single_file` function. There is much more data available there.
2. Reading your comments, it's possible that we really need to report enough Information back to the app and it will publish to prometheus. We don't really get fine-grain info during the transformation of a single file, so there may be little benefit to the transformers reporting.
3. We want total files transformed
4.  I know that the Kubernetes operators can report pod CPU and I/O - it would be great if we could filter in only the pods participating as transformers for a particular request ID - then we could get a lot of real-time info
5. The DID finder really needs to be reporting the rate of replicas being looked up. The DID finder is long-lived so it should be easier to push

**Comment by AndrewEckart** [comment]
> I know that the Kubernetes operators can report pod CPU and I/O - it would be great if we could filter in only the pods participating as transformers for a particular request ID - then we could get a lot of real-time info

Yes, and in fact we already have CPU and I/O [by pod](http://monitoring.uc.ssl-hep.org/d/ab4f13a9892a76a4d21ce8c2445bf4ea/kubernetes-pods?orgId=1). The tricky part is the filtering you describe. I believe it's possible by configuring a Grafana dashboard with a dropdown based on the label values of a certain metric - maybe we can do something like label the transformer pods when they are created programmatically.

> Reading your comments, it's possible that we really need to report enough Information back to the app and it will publish to prometheus. We don't really get fine-grain info during the transformation of a single file, so there may be little benefit to the transformers reporting.

This would save the trouble of using the Pushgateway, but there's some weirdness with doing it from the Flask app. I had added the [Prometheus Flask exporter], which monitors the Flask app itself (i.e. HTTP requests made, statuses, latencies). It's not really clear how to mix that with custom metrics, although we could dump the exporter, which frees up the `/metrics` endpoint for the Prometheus Python client. When the client is used [alongside Flask](https://github.com/prometheus/client_python#flask), the server is supposed to be run with uWSGI. I don't know the consequences of using that instead of gunicorn.

> The DID finder really needs to be reporting the rate of replicas being looked up. The DID finder is long-lived so it should be easier to push

Yeah, I'm going to start with this since it seems like the easiest thing to do by far.
