### ISSUE TITLE
C++ Transformer

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#82]
# Story
_As an Analyzer I want to transform my root dataset using C++ tools so I can access experiment approved libraries_

# Assumptions
1. Will use the EventLoop backend
2. Will generate flat root files
3. Only supported output destination is object-store
4. Will be driven by func_adl select

# Acceptance Criteria
1. Given I have a transform request with a func_adl select When I run the transform then the results should be generated by EventLoop framework

**Comment by gordonwatts** [comment]
Good progress is being made on this. In summary:

- The code generator is "done"
- The transformer works, but needs to be refactored to accommodate a new way to run.

Once the transformer work is done, then it will be time to move onto integration with the ServiceX app.

You can track details of this here: https://github.com/orgs/iris-hep/projects/1

There are two projects already in the ssl-hep repo:
- https://github.com/ssl-hep/ServiceX_Code_Generator_FuncADL_xAOD. Basically ready to be included in ServiceX (minus issues that come up during integration)
- https://github.com/ssl-hep/ServiceX_xAOD_CPP_transformer - Clean up work was done to understand how to alter the C++ running should work. I'm now working back in other packages to refactor to accomodate.

**Comment by gordonwatts** [comment]
With @BenGalewsky help managed to get [code-gen](https://github.com/ssl-hep/ServiceX_Code_Generator_FuncADL_xAOD) part of the way integrated into ServiceX_App. Next steps are testing and then the C++ transformer.

**Comment by gordonwatts** [comment]
On and off over the past few days I've moved this forward a bit. ServiceX will now produce output ROOT files using the C++ transformer. Unfortunately, it won't send those root files to a client yet... The underlying transformer library @BenGalewsky created made a lot of this work easy, thanks!!

Some of my commits desperately need review by @BenGalewsky, of course, they are all in the 82_cpp_transformer branches of the various repos. There were times I just pushed things forward...

1. Preflight for the selection workflow is now totally bypassed. We've talked about eventually needing this, so it could be the right move here is to create a dummy preflight that just says "yes" for now, rather than disturb the logic in ServiceX_App, as I have done.
1. Tests to check the logic in preflight have uncovered some odd bug in now Mock's are built and torn down in the testing framework. See previous message in Slack for some details. But ServiceX_App is no longer passing its tests, but if you run each test individually it works just fine. Sorry about this - am hoping someone more familiar with the Mock framework can fix this.
1. The transformer library needs to have "root-file" added as a valid result-format argument.
1. The transformer library needs a way to, given an output root file, send it to the object store, and report the input file as "done".
1. To make the transformer more "general" from the ServiceX_App's point of view, I altered the way the transformer container is invoked - specifically, it no longer contains the "python" command - just the arguments. This means the words "xAOD" no longer appear in ServiceX_App. This is probably the right way to do things, especially as we move CMS work loads into ServiceX.
1. This change does mean @mweinberg2718's column transformer no longer works. Either is needs to update to the transformer library, or it needs to have its command-line interface replaced (the porxy stuff, along with the python invocation should be updated). I do think it is worth having more than one transformer working, especially b.c. it can do other formats than the C++ one.
1. The sslhep C++ transformer library needs to generate a docker image on commit. Then we need to update tests that use this. :-)

I've littered my updates and commits with "TODO" so you can often see where these things occur.

The blocker item above is the underlying transformer library needs the ability to report a file done and send it to the object store.

I'm sure I've left some stuff off. I've been doing a few hours here and there for a few days. My notes I drew this from aren't always complete!

**Comment by gordonwatts** [comment]
Ok - what is left on this? I think this is done, isn't it?

**Comment by BenGalewsky** [comment]
Yep!
