### ISSUE TITLE
User Provided List of Files to Transform

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#90]
# Story
_As an analyzer I want to provide a list of root files to transform so I can bypass DID finder when I need to_

# Assumptions
1. Will be an optional list of root files in the transform request.
2. If provided, then the DID is optional
3. If a DID is provided, then this is just used as metadata for the results

# Acceptance Criteria
1. Given I have a request with a list of root files and no DID When I submit the request Then the transformation should succeed on the give list of files

**Comment by ivukotic** [comment]
Most of our datasets contain more than 100 files. Most of them exist at more than one place. They can move around. Access endpoint can change. Data storage to a data replica can become inaccessible.  For all these reasons I don't think you want to allow for this option. If someone wants to process only one file for a test he/she should be able to give file scope:filename and get it. did-finder should do the correct thing. As a user I would prefer to be able to say: I want to test this on 1000 events from this dataset so that transformers don't do everything if it's not needed.
just my 2c.
