### ISSUE TITLE
XCache deployment

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#91]
# Story
_As a servicex deployment owner I want to be able to add xcache to the deployment_

# Acceptance Criteria
1. have xcache helm chart
2. have xcache node actually being used by the servicex

**Comment by gordonwatts** [comment]
A few comments on the structure of this:

- I'd say having a working xcache helm chart was an assumption - that is, someone else builds that, and then we use it. So this story can't proceed until someone has done the work to make a good helm chart.
- "have xcache node actually being used by the servicex" - change that to "have the xcache actulally used by"
- Should it be "node"? If the xcache helm chart is done right it will be scalable (like rabbitmq). So it would work as a single node or as a 4 node cluster with 100's of TB's behind it.

But I have another more basic question. Should this xcache helm chart be a dependency of ServiceX? I can see ServiceX running in several environments:

- No XCache at all. Probably just for testing...
- No XCache, but a large data lake because this ServiceX only accepts queries for local datasets...
- A dedicated xcache the site runs just to run with ServiceX
- A XCache that isn't dedicated - that is run as part of a T1 or T2, or some large storage element

Given all of these possibilities here is my idea:
- ServiceX contains no chart to deploy XCache in it
- It contains options that will have it used a configured xcache

Then here at UW I can make my "uw-servicex" chart, it will contains the servicex and xcache as dependencies, and the config to make them use each other.

I partly prefer this approach because it keeps ServiceX lean and mean, keeps the number of dependencies small, and makes the dependency generic (who cares what is actually backing the interface as long as it can parse the now-standard xcache like url). And it allows you to build your site from a set of lego-bricks.

**Comment by ivukotic** [comment]
Hi,

a few answers:
xcache can be scaled to multinode setups.  That adds complexity but can be done in case someone has resources. It is not really possible to get is easily scalable as regular k8s applications, as these nodes should be specially configured. 
OSG creates images for  general XCache, CMS, and ATLAS . Brian Lin is the person that does that. 
https://opensciencegrid.org/docs/data/xrootd/overview/
https://indico.cern.ch/event/727208/contributions/3444631/attachments/1860204/3056905/2019-06-11.XRootD-Workshop.XCache-Packaging.pdf
I am not aware if he makes k8s deployments or helm charts.

I agree that xcache should be an optional part of servicex and not deeply integrated as using xcache is as simply as prepending its address to all the paths.
I would advice against using non-dedicated xcache (from a T2 or T3) as that would significantly effect xcache efficiencies for both uses due different input dataset subsets.

**Comment by BenGalewsky** [comment]
xCache deployment does not belong in our helm chart.
